# Generated by Django 2.0.1 on 2018-01-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180128_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmanager',
            name='add',
        ),
        migrations.AddField(
            model_name='addmanager',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.Add'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='product',
        ),
        migrations.AddField(
            model_name='productmanager',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
            preserve_default=False,
        ),
    ]
