# Generated by Django 2.0.1 on 2018-03-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180327_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
