# Generated by Django 2.0.1 on 2018-12-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
    ]
