# Generated by Django 2.0.1 on 2019-12-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191219_1235'),
        ('product', '0010_auto_20181227_1226'),
    ]

    operations = [
    ]
