# Generated by Django 2.0.1 on 2018-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsection',
            name='icon',
            field=models.CharField(choices=[('1', 'facebook'), ('2', 'vk'), ('3', 'twitter'), ('4', 'google-plus'), ('5', 'instagram')], max_length=32),
        ),
        migrations.AlterField(
            model_name='socialsection',
            name='link',
            field=models.CharField(max_length=256),
        ),
    ]
