# Generated by Django 2.0.1 on 2018-02-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20180128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsection',
            name='icon',
            field=models.CharField(choices=[('facebook', 'facebook'), ('vk', 'vk'), ('twitter', 'twitter'), ('google-plus', 'google-plus'), ('instagram', 'instagram')], max_length=32),
        ),
    ]
