# Generated by Django 2.0.1 on 2018-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180128_1136'),
        ('section', '0002_auto_20180128_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('related_categories', models.ManyToManyField(to='category.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='socialsection',
            name='icon',
            field=models.CharField(choices=[('facebook', 'facebook'), ('vk', 'vk'), ('twitter', 'twitter'), ('google-plus', 'google-plus'), ('instagram', 'instagram')], max_length=32),
        ),
    ]
