# Generated by Django 2.0.1 on 2018-02-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20180201_0555'),
        ('section', '0004_emailsection'),
    ]

    operations = [
    ]
