# Generated by Django 2.0.1 on 2018-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_merge_20180225_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_mark', models.FloatField(default=4.5)),
                ('count', models.IntegerField(default=17)),
            ],
        ),
    ]
