# Generated by Django 2.0.1 on 2018-02-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_merge_20180228_0840'),
        ('section', '0006_footersectiontext_votes'),
    ]

    operations = [
    ]
