# Generated by Django 2.0.1 on 2018-03-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_merge_20180228_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='icon',
            field=models.CharField(choices=[('kyivstar', 'kyivstar'), ('vodafone', 'vodafone'), ('lifecell', 'lifecell')], default='', max_length=32),
            preserve_default=False,
        ),
    ]
