# Generated by Django 2.0.1 on 2018-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_contactsection_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharessection',
            name='show_at_main',
            field=models.BooleanField(default=True, verbose_name='Показувати на головній'),
        ),
        migrations.AddField(
            model_name='sharessection',
            name='show_at_shares',
            field=models.BooleanField(default=True, verbose_name='Показувати в акціях'),
        ),
    ]
