# Generated by Django 2.0.1 on 2018-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180128_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='Відображати'),
        ),
    ]
