# Generated by Django 2.0.1 on 2018-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[('cache', 'Cache'), ('card', 'Card')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
