# Generated by Django 2.0.1 on 2018-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_type_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[('0', 'cache'), ('1', 'card')], max_length=32),
        ),
    ]
