# Generated by Django 2.0.1 on 2018-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180128_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adds',
            field=models.ManyToManyField(blank=True, to='product.AddManager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.ProductManager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[(0, 'cache'), (1, 'card')], default=0, max_length=32),
        ),
    ]
