# Generated by Django 2.0.1 on 2018-04-11 17:32

from django.db import migrations, models
# import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментарій'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=256, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, verbose_name='Всього'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[('0', 'Готівка'), ('1', 'Картка')], default=0, max_length=32, verbose_name='Тип платежу'),
        ),
    ]
