# Generated by Django 2.0.1 on 2018-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180411_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.FloatField(blank=True, default=0, verbose_name='Всього зі знижкою'),
            preserve_default=False,
        ),
    ]
