# Generated by Django 2.0.1 on 2018-12-29 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20181227_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
