# Generated by Django 2.0.1 on 2019-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
