# Generated by Django 2.0.1 on 2018-12-30 11:50

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_auto_20181227_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=order.models.uuid_str, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('simple_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256, verbose_name="Ім'я")),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('address', models.CharField(max_length=256, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефону')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарій')),
                ('type_of_payment', models.CharField(choices=[('0', 'Готівка'), ('1', 'Картка')], default=0, max_length=32, verbose_name='Тип платежу')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('total', models.FloatField(blank=True, verbose_name='Всього')),
                ('total_discount', models.FloatField(blank=True, verbose_name='Всього зі знижкою')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adds', models.ManyToManyField(blank=True, to='product.AddManager')),
                ('product', models.ManyToManyField(blank=True, to='product.ProductManager')),
            ],
        ),
    ]
