# Generated by Django 2.0.1 on 2018-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180128_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
    ]
