# Generated by Django 2.0.1 on 2018-04-11 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_total_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
